apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteOnce # Change to ReadWriteMany if using NFS/Cloud Filestore
  resources:
    requests:
      storage: 1Gi
